name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
    tags-ignore:
      # This will ignore release versions tagged with a version identifier. We'll
      # use a separate workflow for them.
      - "v*"
  pull_request:
    paths-ignore:
      - README.md
      - "CHANGELOG.md"
      - ".gitignore"

jobs:
  build:
    uses: ilyvion/rimworld-utils/.github/workflows/build_mod.yml@main
    with:
      mod_name: "EnhancedBeliefs-Updated"
      artifact_suffix: ${{ github.sha }}
      rw_versions: |-
        1.5
        1.6
      extra_files: |-
        Royalty
